insert into teams (id, name, abbreviation, Users_id) values (1, 'Flowdesk', 'FDK', 11);
insert into teams (id, name, abbreviation, Users_id) values (2, 'Zontrax', 'ZTX', 1);
insert into teams (id, name, abbreviation, Users_id) values (3, 'Fnatic', 'FNC', 6);
insert into teams (id, name, abbreviation, Users_id) values (4, 'Voltsillam', 'VSM', 3);
insert into teams (id, name, abbreviation, Users_id) values (5, 'Flexidy', 'FXY', 13);
insert into teams (id, name, abbreviation, Users_id) values (6, 'Cardguard', 'CGD', 7);
insert into teams (id, name, abbreviation, Users_id) values (7, 'Veribet', 'VBT', 2);
insert into teams (id, name, abbreviation, Users_id) values (8, 'Viva', 'Viva', 8);
insert into teams (id, name, abbreviation, Users_id) values (9, 'Home Ing', 'HI', 13);
insert into teams (id, name, abbreviation, Users_id) values (10, 'Tresomcorp', 'TCP' , 3);
insert into teams (id, name, abbreviation, Users_id) values (11, 'lafrenchcolection', 'LFC' , 2);