insert into locations (id, Name, Adress) values (1, 'Bamity', '33664 Sachtjen Parkway');
insert into locations (id, Name, Adress) values (2, 'Toughjoyfax', '330 Transport Hill');
insert into locations (id, Name, Adress) values (3, 'Stronghold', '0 Warner Way');
insert into locations (id, Name, Adress) values (4, 'Holdlamis', '7 Novick Street');
insert into locations (id, Name, Adress) values (5, 'Bytecard', '55802 Sage Place');
insert into locations (id, Name, Adress) values (6, 'Span', '8 Mandrake Circle');
insert into locations (id, Name, Adress) values (7, 'Bytecard', '4 Elka Road');
insert into locations (id, Name, Adress) values (8, 'Sonsing', '200 Donald Street');
insert into locations (id, Name, Adress) values (9, 'Trippledex', '003 Merrick Alley');
insert into locations (id, Name, Adress) values (10, 'Bitchip', '6 John Wall Center');
