insert into tournaments (id, game, max_teams, name) values (1, 'Zicam', 331, 'Y-Solowarm');
insert into tournaments (id, game, max_teams, name) values (2, 'Bryophyllum e fol. 10', 60, 'Domainer');
insert into tournaments (id, game, max_teams, name) values (3, 'Head and Shoulders', 310, 'Treeflex');
insert into tournaments (id, game, max_teams, name) values (4, 'ISA KNOX WXII PLUS WHITENING REVOLUTION SERUM', 392, 'Gembucket');
insert into tournaments (id, game, max_teams, name) values (5, 'Grains and Gluten Intolerances', 182, 'Greenlam');
insert into tournaments (id, game, max_teams, name) values (6, 'Coppertone Tanning Dry Oil', 29, 'Wrapsafe');
insert into tournaments (id, game, max_teams, name) values (7, 'Lotrel', 7, 'Zoolab');
insert into tournaments (id, game, max_teams, name) values (8, 'Prednisone', 318, 'Prodder');
insert into tournaments (id, game, max_teams, name) values (9, 'Goongsecret Calming Bath', 348, 'Glltournament');
insert into tournaments (id, game, max_teams, name) values (10, 'Oxygen', 155, 'Daltfresh');
