-- MySQL Script generated by MySQL Workbench
-- Tue May 18 09:09:03 2021
-- Model: elan    Version: 1.1.1
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema elan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `elan`;
-- -----------------------------------------------------
-- Schema elan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elan` DEFAULT CHARACTER SET utf8;
USE `elan`;
-- -----------------------------------------------------
-- Table `elan`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueRole` (`name` ASC)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueImage` (`path` ASC) VISIBLE)
 ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `role_id` INT NULL,
  `image_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Roles1_idx` (`role_id` ASC),
  UNIQUE INDEX `UniqueUserUsername` (`username` ASC),
  INDEX `fk_users_images1_idx` (`image_id` ASC),
  UNIQUE INDEX `UniqueUserEmail` (`email` ASC),
  CONSTRAINT `fk_Users_Roles1` FOREIGN KEY (`role_id`) REFERENCES `elan`.`roles` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_images1` FOREIGN KEY (`image_id`) REFERENCES `elan`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION

) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueState` (`type` ASC)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`lans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`lans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NULL,
  `places` INT NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `state_id` INT NOT NULL,
  `images_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueLan` (`name` ASC),
  INDEX `fk_Lans_Stats1_idx` (`state_id` ASC),
  INDEX `fk_lans_images1_idx` (`images_id` ASC),
  CONSTRAINT `fk_Lans_Stats1` FOREIGN KEY (`state_id`) REFERENCES `elan`.`states` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_lans_images1` FOREIGN KEY (`images_id`) REFERENCES `elan`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
  
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueLocation` (`name` ASC, `address` ASC)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NULL,
  `type` VARCHAR(64) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `image_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_images1_idx` (`image_id` ASC),
  UNIQUE INDEX `UnqiqueEvent` (`name` ASC, `start` ASC, `end` ASC),
  CONSTRAINT `fk_events_images1` FOREIGN KEY (`image_id`) REFERENCES `elan`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `abbreviation` VARCHAR(5) NOT NULL,
  `owner_id` INT NULL,
  `images_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueTeam` (`name` ASC) VISIBLE,
  INDEX `fk_Teams_Users1_idx` (`owner_id` ASC) INVISIBLE,
  INDEX `fk_teams_images1_idx` (`images_id` ASC) VISIBLE,
  CONSTRAINT `fk_Teams_Users1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `elan`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teams_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `elan`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`tournaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`tournaments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game` VARCHAR(64) NOT NULL,
  `max_teams` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueTournament` (`name` ASC)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`matches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` DATETIME NOT NULL,
  `end` DATETIME NULL,
  `match_number` INT NOT NULL,
  `score_team1` INT NULL,
  `score_team2` INT NULL,
  `team1_id` INT NOT NULL,
  `team2_id` INT NOT NULL,
  `tournament_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Matches_Teams_idx` (`team1_id` ASC),
  INDEX `fk_Matches_Teams1_idx` (`team2_id` ASC),
  INDEX `fk_Matches_Tournaments1_idx` (`tournament_id` ASC),
  UNIQUE INDEX `UniqueMatch` (`match_number` ASC),
  CONSTRAINT `fk_Matches_Teams` FOREIGN KEY (`team1_id`) REFERENCES `elan`.`teams` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matches_Teams1` FOREIGN KEY (`team2_id`) REFERENCES `elan`.`teams` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matches_Tournaments1` FOREIGN KEY (`tournament_id`) REFERENCES `elan`.`tournaments` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`tournament_is_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`tournament_is_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tournament_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  INDEX `fk_Tournaments_has_Events_Events1_idx` (`event_id` ASC),
  INDEX `fk_Tournaments_has_Events_Tournaments1_idx` (`tournament_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueTournamentEvent` (`tournament_id` ASC, `event_id` ASC),
  CONSTRAINT `fk_Tournaments_has_Events_Tournaments1` FOREIGN KEY (`tournament_id`) REFERENCES `elan`.`tournaments` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tournaments_has_Events_Events1` FOREIGN KEY (`event_id`) REFERENCES `elan`.`events` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`lan_contains_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`lan_contains_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lan_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  INDEX `fk_Events_has_Lans_Lans1_idx` (`lan_id` ASC),
  INDEX `fk_Events_has_Lans_Events1_idx` (`event_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueLanEvent` (`lan_id` ASC, `event_id` ASC),
  CONSTRAINT `fk_Events_has_Lans_Events1` FOREIGN KEY (`event_id`) REFERENCES `elan`.`events` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Lans_Lans1` FOREIGN KEY (`lan_id`) REFERENCES `elan`.`lans` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`team_participate_in_tournament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`team_participate_in_tournament` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT NOT NULL,
  `tournament_id` INT NOT NULL,
  INDEX `fk_Tournaments_has_Teams_Teams1_idx` (`team_id` ASC),
  INDEX `fk_Tournaments_has_Teams_Tournaments1_idx` (`tournament_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueParticipation` (`team_id` ASC, `tournament_id` ASC),
  CONSTRAINT `fk_Tournaments_has_Teams_Tournaments1` FOREIGN KEY (`tournament_id`) REFERENCES `elan`.`tournaments` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tournaments_has_Teams_Teams1` FOREIGN KEY (`team_id`) REFERENCES `elan`.`teams` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`event_is_at_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`event_is_at_location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  INDEX `fk_Events_has_Locations_Locations1_idx` (`location_id` ASC),
  INDEX `fk_Events_has_Locations_Events1_idx` (`event_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueEventLocation` (`event_id` ASC, `location_id` ASC),
  CONSTRAINT `fk_Events_has_Locations_Events1` FOREIGN KEY (`event_id`) REFERENCES `elan`.`events` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Locations_Locations1` FOREIGN KEY (`location_id`) REFERENCES `elan`.`locations` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`user_register_to_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`user_register_to_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `fk_Events_has_Users_Users1_idx` (`user_id` ASC),
  INDEX `fk_Events_has_Users_Events1_idx` (`event_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UnqiqueUserEvent` (`event_id` ASC, `user_id` ASC),
  CONSTRAINT `fk_Events_has_Users_Events1` FOREIGN KEY (`event_id`) REFERENCES `elan`.`events` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Users_Users1` FOREIGN KEY (`user_id`) REFERENCES `elan`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `elan`.`user_joins_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elan`.`user_joins_team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  INDEX `fk_Teams_has_Users_Users1_idx` (`user_id` ASC),
  INDEX `fk_Teams_has_Users_Teams1_idx` (`team_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueUserTeam` (`user_id` ASC, `team_id` ASC),
  CONSTRAINT `fk_Teams_has_Users_Teams1` FOREIGN KEY (`team_id`) REFERENCES `elan`.`teams` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_has_Users_Users1` FOREIGN KEY (`user_id`) REFERENCES `elan`.`users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;